In [1]:
import numpy as np
import pandas as pd

<b> Q1

In [11]:
data = np.random.uniform(low = -100, high = 100, size= (100,100))
data

array([[ 23.6765503 ,  57.63541246,  23.19750762, ..., -65.62934733,
         27.52431098, -77.84352037],
       [ 10.50646595, -65.22209072, -74.15763652, ...,  96.81156886,
         42.28593491,  -2.17619755],
       [ 55.46564603, -65.51406805, -87.25111872, ...,  42.68798138,
        -53.08518444, -38.16372668],
       ...,
       [-57.52129332,  93.27038372,  40.44554855, ..., -52.63673501,
         20.13497842, -76.76914475],
       [-42.42032225,  23.89958231,  69.29252254, ...,  12.73206983,
        -52.22951038,  54.50458331],
       [-62.08343362, -98.67381704,  12.22045165, ...,  51.83832696,
         16.75716818, -57.07155136]], shape=(100, 100))

In [15]:
print(f'Euclidean distance matrix :')
euclidean_dist = np.sqrt(((data[:, np.newaxis, :] - data[np.newaxis, :, :]) ** 2).sum(axis=-1))
print(euclidean_dist)

Euclidean distance matrix :
[[  0.         867.1231017  771.11821001 ... 789.56008029 810.36579272
  855.12374638]
 [867.1231017    0.         815.69213926 ... 852.97635935 807.42432258
  787.26431795]
 [771.11821001 815.69213926   0.         ... 775.07631914 904.86096057
  789.80336457]
 ...
 [789.56008029 852.97635935 775.07631914 ...   0.         750.41631695
  789.20700525]
 [810.36579272 807.42432258 904.86096057 ... 750.41631695   0.
  785.49781811]
 [855.12374638 787.26431795 789.80336457 ... 789.20700525 785.49781811
    0.        ]]


In [14]:
norms = np.linalg.norm(data, axis=1, keepdims=True)
cosine_sim = np.dot(data, data.T) / (norms * norms.T)
print(cosine_sim)

[[ 1.         -0.13365659  0.07833428 ...  0.01621324 -0.01047428
  -0.19690909]
 [-0.13365659  1.         -0.01065733 ... -0.12490798  0.01679182
   0.00729249]
 [ 0.07833428 -0.01065733  1.         ...  0.04454505 -0.26950954
  -0.02904047]
 ...
 [ 0.01621324 -0.12490798  0.04454505 ...  1.          0.11108659
  -0.04731549]
 [-0.01047428  0.01679182 -0.26950954 ...  0.11108659  1.
  -0.00995352]
 [-0.19690909  0.00729249 -0.02904047 ... -0.04731549 -0.00995352
   1.        ]]


<b> Qn 2

In [17]:
data = np.random.randint(0, 20, size=(100, 100))
data

array([[ 1, 19,  3, ...,  7, 18,  1],
       [18, 16, 14, ...,  7, 17, 18],
       [18, 12, 14, ...,  6,  4, 19],
       ...,
       [ 4, 16,  5, ...,  9,  6, 13],
       [ 1, 14, 11, ...,  1, 17, 12],
       [15,  9, 15, ...,  7, 13, 13]], shape=(100, 100))

In [18]:
matches = (data[:, np.newaxis, :] == data[np.newaxis, :, :])
m = np.sum(matches, axis=-1)
p = data.shape[1]
dissimilarity_matrix = (p - m) / p
print("dissimilarity matrix")
dissimilarity_matrix

dissimilarity matrix


array([[0.  , 0.95, 0.97, ..., 0.95, 0.93, 0.95],
       [0.95, 0.  , 0.96, ..., 0.94, 0.93, 0.95],
       [0.97, 0.96, 0.  , ..., 0.94, 0.94, 0.92],
       ...,
       [0.95, 0.94, 0.94, ..., 0.  , 0.93, 0.96],
       [0.93, 0.93, 0.94, ..., 0.93, 0.  , 0.95],
       [0.95, 0.95, 0.92, ..., 0.96, 0.95, 0.  ]], shape=(100, 100))

<b> Q3

In [20]:
data = np.random.randint(0, 2, size=(100, 100))
data

array([[0, 1, 1, ..., 1, 0, 1],
       [1, 1, 1, ..., 1, 1, 0],
       [1, 0, 0, ..., 1, 0, 1],
       ...,
       [0, 0, 0, ..., 1, 1, 0],
       [1, 0, 1, ..., 0, 1, 1],
       [1, 0, 1, ..., 0, 0, 0]], shape=(100, 100))

In [21]:
i_eq_1 = data[:, np.newaxis, :] == 1
j_eq_1 = data[np.newaxis, :, :] == 1

q = np.sum(i_eq_1 & j_eq_1, axis=-1)       
r = np.sum(i_eq_1 & ~j_eq_1, axis=-1)      
s = np.sum(~i_eq_1 & j_eq_1, axis=-1)      
t = np.sum(~i_eq_1 & ~j_eq_1, axis=-1)

denominator = q + r + s + t                
numerator = r + s

dissimilarity_matrix = numerator / denominator.astype(float)
print("dissimilarity_matrix")
dissimilarity_matrix

dissimilarity_matrix


array([[0.  , 0.45, 0.41, ..., 0.47, 0.49, 0.53],
       [0.45, 0.  , 0.54, ..., 0.5 , 0.48, 0.58],
       [0.41, 0.54, 0.  , ..., 0.48, 0.56, 0.56],
       ...,
       [0.47, 0.5 , 0.48, ..., 0.  , 0.52, 0.48],
       [0.49, 0.48, 0.56, ..., 0.52, 0.  , 0.52],
       [0.53, 0.58, 0.56, ..., 0.48, 0.52, 0.  ]], shape=(100, 100))

<b> Qn4

In [26]:
data = np.random.randint(1, 10, size=(100,))
normalized = (data - 1) / (10 - 1)
normalized_2d = normalized[:, np.newaxis]  
distance_matrix = np.sqrt((normalized_2d - normalized_2d.T)**2)
print(distance_matrix)

[[0.         0.22222222 0.         ... 0.44444444 0.33333333 0.22222222]
 [0.22222222 0.         0.22222222 ... 0.66666667 0.11111111 0.        ]
 [0.         0.22222222 0.         ... 0.44444444 0.33333333 0.22222222]
 ...
 [0.44444444 0.66666667 0.44444444 ... 0.         0.77777778 0.66666667]
 [0.33333333 0.11111111 0.33333333 ... 0.77777778 0.         0.11111111]
 [0.22222222 0.         0.22222222 ... 0.66666667 0.11111111 0.        ]]
